<?php
/**
 * @copyright ©2019 浙江禾匠信息科技
 * Created by PhpStorm.
 * User: Andy - Wangjie
 * Date: 2019/7/4
 * Time: 11:22
 */

namespace app\plugins\bonus\controllers\api;

use app\core\response\ApiCode;
use app\plugins\bonus\models\BonusSetting;

class ApiController extends \app\controllers\api\ApiController
{
    public function beforeAction($action)
    {
        //权限判断
        $permission = \Yii::$app->branch->childPermission(\Yii::$app->mall->user->adminInfo);
        if (!in_array('bonus', $permission)) {
            \Yii::$app->response->data = ['code' => ApiCode::CODE_ERROR, 'msg' => '无团队分红权限'];
            return false;
        }
        //判断分红开关
        $model = BonusSetting::findOne(['mall_id' => \Yii::$app->mall->id, 'key' => 'is_bonus', 'value' => '1', 'is_delete' => 0]);
        if (empty($model)) {
            \Yii::$app->response->data = ['code' => ApiCode::CODE_ERROR, 'msg' => '团队分红已关闭'];
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
