<?php
/**
 * Created by zjhj_mall_v4
 * User: jack_guo
 * Date: 2020/3/17
 * Email: <657268722@qq.com>
 */

namespace app\plugins\region\models;

class Order extends \app\models\Order
{
    public function getRegionOrder()
    {
        return $this->hasOne(RegionOrder::className(), ['order_id' => 'id']);
    }

    public function getOrderActionStatus($order)
    {
        $order = parent::getOrderActionStatus($order); // TODO: Change the autogenerated stub

        $order['is_print_send_template'] = 0;

        return $order;
    }
}