<?php
/**
 * link: http://www.zjhejiang.com/
 * copyright: Copyright (c) 2018 浙江禾匠信息科技有限公司
 * author: jack_guo
 */

namespace app\forms\mall\export;

use app\core\CsvExport;

class PintuanStatisticsExport extends BaseExport
{

    public function fieldsList()
    {
        return [
            [
                'key' => 'name',
                'value' => '商品名称',
            ],
            [
                'key' => 'all_user',
                'value' => '拼团人数',
            ],
            [
                'key' => 'success_user',
                'value' => '成团人数',
            ],
            [
                'key' => 'success_100',
                'value' => '成团率',
            ],
            [
                'key' => 'pay_user',
                'value' => '支付人数',
            ],
            [
                'key' => 'goods_num',
                'value' => '支付件数',
            ],
            [
                'key' => 'total_pay_price',
                'value' => '支付金额',
            ],
            [
                'key' => 'status',
                'value' => '状态',
            ],
        ];
    }

    public function export($query)
    {
        $list = $query
            ->asArray()
            ->all();
        $this->transform($list);
        $this->getFields();
        $dataList = $this->getDataList();

        $fileName = '拼团统计' . date('YmdHis');
        (new CsvExport())->export($dataList, $this->fieldsNameList, $fileName);
    }

    protected function transform($list)
    {
        $newList = [];
        $arr = [];

        $number = 1;
        foreach ($list as $key => $item) {
            $arr['number'] = $number++;
            $arr['success_100']=(($item['all_user'] == 0) ? 0 : (bcdiv($item['success_user'], $item['all_user'], 4) * 100)) . '%';
            $item['all_user'] = intval($item['all_user']);
            $item['success_user'] = intval($item['success_user']);
            $item['pay_user'] = intval($item['pay_user']);
            $item['goods_num'] = intval($item['goods_num']);
            $item['total_pay_price'] = floatval($item['total_pay_price']);

            $arr = array_merge($arr, $item);

            $newList[] = $arr;
        }
        $this->dataList = $newList;
    }

    protected function getFields()
    {
        $arr = [];
        foreach ($this->fieldsList() as $key => $item) {
            $arr[$key] = $item['key'];
        }
        $this->fieldsKeyList = $arr;
        parent::getFields(); // TODO: Change the autogenerated stub
    }
}
