<?php
/**
 * link: http://www.zjhejiang.com/
 * copyright: Copyright (c) 2018 浙江禾匠信息科技有限公司
 * author: zbj
 */

namespace app\plugins\advance\controllers\api;


use app\core\response\ApiCode;
use app\plugins\advance\forms\common\SettingForm;

class ApiController extends \app\controllers\api\ApiController
{
    public function beforeAction($action)
    {
        //权限判断
        $permission = \Yii::$app->branch->childPermission(\Yii::$app->mall->user->adminInfo);
        if (!in_array('advance', $permission)) {
            \Yii::$app->response->data = ['code' => ApiCode::CODE_ERROR, 'msg' => '无商品预售权限'];
            return false;
        }
        //判断预售开关
        $setting = (new SettingForm())->search();
        if ($setting['is_advance'] == 0) {
            \Yii::$app->response->data = ['code' => ApiCode::CODE_ERROR, 'msg' => '商品预售已关闭'];
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
